### ISSUE TITLE
how to pass GFXFont address in javascript setFont function.

### ISSUE THREAD

**Issue by engrziarehman** [mongoose-os-libs/ili9341-spi#10]
i am using this library in with esp32 and ili9341 lcd, all graphics functionality is working fine, except fonts selection and printing. need an example code or way to set font and print in javascript.

**Comment by pimvanpelt** [comment]
Assigning to nlilviu who submitted the javascript code. I personally don't use it, so I won't be able to answer questions on JavaScript use.

**Comment by rojer** [comment]
check out https://github.com/mongoose-os-apps/example-m5stack-js

**Comment by pimvanpelt** [comment]
Thanks, @rojer that explains it quite nicely with an example.
@engrziarehman take a look at the C helper function `get_font()`:
https://github.com/mongoose-os-apps/example-m5stack-js/blob/master/src/main.c

which is then introduced with `ffi()` in javascript:
```
let getFont = ffi('void* get_font(int)');
let fonts = [getFont(0), getFont(1), getFont(2), getFont(3)];
```

Then you can call it in JavaScript:
```
ILI9341.setFont(fonts[1]);
```

**Comment by engrziarehman** [comment]
thank you, why don't you add this in README file, the usage of setFont().
