### ISSUE TITLE
Font conversion script?

### ISSUE THREAD

**Issue by tripflex** [mongoose-os-libs/ili9341-spi#15]
I'm looking to convert some additional fonts, but it looks like you must have customized the adafruit `gfxfont.h` file and added to the `GFXfont` struct

... did you customize the fontconvert file as well or did you just manually edit each one of those files?  I was able to manually edit them myself to get them to work, but if you have the edited fontconvert script that would be useful for those who want to convert additional fonts ...

**Comment by pimvanpelt** [comment]
I scripted the additions to `GFXfont` and the header files. I did not edit fontconvert. User supplied fonts should be in another git repository, so adding a fontconverter is not super useful.

**Comment by tripflex** [comment]
No problem, i'll go ahead and close this.  

For reference, I did hack apart the fontconvert real quick to allow converting fonts to work with the struct in this library, if anybody wants it you can find a copy here:
https://gist.github.com/tripflex/f2e2ff2d86ab9c470205b276f0ab3858
